#
# config file for RUN.sh
#


############################### Python Version
PYTHON="python3.12"


############################## Logging
LOG_FILE="run.log"
APPEND_LOG=false # true to append, false to overwrite the logs


############################## Runners
# set to false to skip the step or true to run it
TOKENIZERS=false
EXAMINE=false
TRAIN_LM=true
EVAL_LM=true
PLOT_LM=true


############################## train_lm.py / evaluate_lm.py
# tokenizers to train and evaluate a language model for (any of the names in config.MODELS)
LM_TOKENIZERS="Character-Level CharLevelBPE_2000 CharLevelBPE_10000 ByteLevelBPE_2000 ByteLevelBPE_10000"
# optional
EPOCHS_LM=10
CONTEXT_LENGTH=256
BATCH_SIZE=32
LEARNING_RATE=0.001
HIDDEN_DIM=256
N_HEADS=4
FF_DIM=1024
N_LAYERS=2
DROPOUT=0.1
SEED=0


############################## evaluate_lm.py
EVAL_SPLIT="valid" # valid or test

############################### plot_lm.py
PLOT_SPLIT="valid" # valid or test
